import {Book,Task,Business,MoneyEntry,Launch,Note} from './types';
export const seed={
books:[{id:'b1',title:'Hot Mess in Heels',series:'Hot Mess Chronicles',genre:'Contemporary Romance',status:'Drafting',word_count:42000,next_step:'Finish Act 2',launch_date:'2026-07-18',notes:'Need beta readers'},{id:'b2',title:'A Mother\'s Love: Redemption',series:'A Mother\'s Love',genre:'Women\'s Fiction',status:'Editing',word_count:68000,next_step:'Line edits',launch_date:'2026-08-30',notes:''},{id:'b3',title:'Ratchet Royalty: Crowned',series:'Ratchet Royalty',genre:'Urban Romance',status:'Outline',word_count:9000,next_step:'Complete character arcs',launch_date:'2026-10-01',notes:''},{id:'b4',title:'Ashes of the Thorn Queen',series:'Dark Fantasy Romance',genre:'Fantasy Romance',status:'Idea',word_count:0,next_step:'Worldbuilding notes',launch_date:'2027-02-10',notes:''},{id:'b5',title:'Legacy in Ink',series:'Memoir Project',genre:'Memoir',status:'Drafting',word_count:22000,next_step:'Interview family members',launch_date:'2027-01-15',notes:''}] as Book[],
tasks:[{id:'t1',task_name:'Finalize cover brief',category:'Books',linked_to_type:'book',linked_to_name:'Hot Mess in Heels',priority:'High',status:'To Do',due_date:'2026-05-06',owner:'Quachell',notes:''},{id:'t2',task_name:'Follow up enterprise lead',category:'Roherri',linked_to_type:'business',linked_to_name:'Roherri Agile Solutions',priority:'High',status:'In Progress',due_date:'2026-05-05',owner:'Quachell',notes:''}] as Task[],
businesses:[{id:'bus1',name:'Roherri Agile Solutions',leads:14,clients:6,proposals:5,contracts:3,revenue:32000,follow_ups:'3 this week',notes:''},{id:'bus2',name:'Roherri Tech Academy',leads:33,clients:12,proposals:4,contracts:8,revenue:41000,follow_ups:'webinar list',notes:''},{id:'bus3',name:'Roherri Legacy Advisors',leads:7,clients:4,proposals:2,contracts:2,revenue:11500,follow_ups:'Tax strategist',notes:''},{id:'bus4',name:'JobTrackr',leads:120,clients:37,proposals:9,contracts:16,revenue:27500,follow_ups:'Partnership outreach',notes:''},{id:'bus5',name:'Glyco Health',leads:20,clients:9,proposals:3,contracts:3,revenue:17800,follow_ups:'Clinic onboarding',notes:''}] as Business[],
money:[{id:'m1',type:'income',category:'Book Sales',amount:2400,date:'2026-05-01',notes:''},{id:'m2',type:'income',category:'Consulting',amount:5200,date:'2026-05-02',notes:''},{id:'m3',type:'expense',category:'Software',amount:399,date:'2026-05-03',notes:''}] as MoneyEntry[],
launches:[{id:'l1',launch_name:'Hot Mess in Heels Launch',product:'Book',platform:'Amazon KDP',launch_date:'2026-07-18',status:'planned',checklist:'Cover, ARC, ads',revenue_goal:10000,notes:''}] as Launch[],
notes:[{id:'n1',title:'Campaign Angle',category:'Launch',body:'Use enemies-to-lovers snippets for ad hooks.',linked_to:'Hot Mess in Heels',created_at:'2026-05-01'}] as Note[]
};
